In [4]:
from tensorflow.keras.preprocessing.text import one_hot


In [5]:
sentences = [
    "I love learning artificial intelligence",
    "Machine learning is a powerful technology",
    "Deep learning is a part of machine learning",
    "Artificial intelligence is changing the world",
    "Python is widely used for machine learning",
    "Java is a popular programming language",
    "I enjoy writing Python programs",
    "Data science involves statistics and programming",
    "Natural language processing works with human language",
    "Word embeddings represent words as vectors",
    "Machine learning models learn from data",
    "Deep learning uses neural networks",
    "Neural networks are inspired by the human brain",
    "Technology is developing very quickly",
    "Students learn programming through practice",
    "Programming requires logical thinking",
    "I practice coding every day",
    "Artificial intelligence has many applications",
    "Robotics combines software and hardware",
    "AI and robotics are interesting fields"
]

In [6]:
##Define vocaublary size
voc_size=10000

In [ ]:
###one hot representaion for every word
one_hot_representaion=[one_hot(words,voc_size)for words in sentences]
one_hot_representaion

[[458, 8264, 4343, 8080, 446],
 [2773, 4343, 4273, 7670, 604, 855],
 [9477, 4343, 4273, 7670, 9107, 2330, 2773, 4343],
 [8080, 446, 4273, 1538, 1122, 8896],
 [2906, 4273, 6542, 716, 155, 2773, 4343],
 [2613, 4273, 7670, 7443, 6092, 9232],
 [458, 2060, 8195, 2906, 999],
 [6628, 1614, 660, 1097, 9001, 6092],
 [1031, 9232, 8966, 6705, 7974, 6295, 9232],
 [858, 6013, 8389, 9658, 1824, 7849],
 [2773, 4343, 1878, 6627, 4445, 6628],
 [9477, 4343, 1953, 4036, 3317],
 [4036, 3317, 7560, 9155, 3824, 1122, 6295, 1290],
 [855, 4273, 9613, 7508, 2545],
 [3933, 6627, 6092, 5346, 9984],
 [6092, 2378, 621, 8455],
 [458, 9984, 9756, 4109, 4703],
 [8080, 446, 900, 6400, 7454],
 [3737, 3201, 4261, 9001, 9626],
 [800, 9001, 3737, 7560, 7795, 7640]]

In [8]:
## word embedding representation
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np


In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_representaion,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0  458 8264 4343 8080  446]
 [   0    0 2773 4343 4273 7670  604  855]
 [9477 4343 4273 7670 9107 2330 2773 4343]
 [   0    0 8080  446 4273 1538 1122 8896]
 [   0 2906 4273 6542  716  155 2773 4343]
 [   0    0 2613 4273 7670 7443 6092 9232]
 [   0    0    0  458 2060 8195 2906  999]
 [   0    0 6628 1614  660 1097 9001 6092]
 [   0 1031 9232 8966 6705 7974 6295 9232]
 [   0    0  858 6013 8389 9658 1824 7849]
 [   0    0 2773 4343 1878 6627 4445 6628]
 [   0    0    0 9477 4343 1953 4036 3317]
 [4036 3317 7560 9155 3824 1122 6295 1290]
 [   0    0    0  855 4273 9613 7508 2545]
 [   0    0    0 3933 6627 6092 5346 9984]
 [   0    0    0    0 6092 2378  621 8455]
 [   0    0    0  458 9984 9756 4109 4703]
 [   0    0    0 8080  446  900 6400 7454]
 [   0    0    0 3737 3201 4261 9001 9626]
 [   0    0  800 9001 3737 7560 7795 7640]]


In [11]:
## feature representataion
dim=10


In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 164ms/step


array([[[-0.00086222,  0.01436532, -0.03679921, ...,  0.00363304,
          0.04126878, -0.03367127],
        [-0.00086222,  0.01436532, -0.03679921, ...,  0.00363304,
          0.04126878, -0.03367127],
        [-0.00086222,  0.01436532, -0.03679921, ...,  0.00363304,
          0.04126878, -0.03367127],
        ...,
        [-0.02065004,  0.03175913,  0.00026436, ...,  0.02553776,
          0.02138444,  0.01912861],
        [-0.04712678, -0.00592683, -0.02656016, ...,  0.01174365,
         -0.02729791, -0.04543424],
        [ 0.02649206,  0.04398872,  0.03225647, ..., -0.00069368,
         -0.00364696, -0.02831121]],

       [[-0.00086222,  0.01436532, -0.03679921, ...,  0.00363304,
          0.04126878, -0.03367127],
        [-0.00086222,  0.01436532, -0.03679921, ...,  0.00363304,
          0.04126878, -0.03367127],
        [-0.01784408, -0.00957599, -0.00242209, ..., -0.02378392,
         -0.02034518,  0.02372557],
        ...,
        [ 0.03286118, -0.01167626, -0.04690259, ...,  

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 36ms/step


array([[-0.00086222,  0.01436532, -0.03679921,  0.02838781, -0.03944111,
        -0.002326  , -0.0324677 ,  0.00363304,  0.04126878, -0.03367127],
       [-0.00086222,  0.01436532, -0.03679921,  0.02838781, -0.03944111,
        -0.002326  , -0.0324677 ,  0.00363304,  0.04126878, -0.03367127],
       [-0.00086222,  0.01436532, -0.03679921,  0.02838781, -0.03944111,
        -0.002326  , -0.0324677 ,  0.00363304,  0.04126878, -0.03367127],
       [ 0.02486774, -0.03147805, -0.01335352, -0.01428775,  0.03521765,
        -0.03365588,  0.02161721,  0.04530188,  0.0476338 ,  0.02363804],
       [ 0.0310686 , -0.02771785, -0.02940211,  0.04477936,  0.04563564,
         0.01259005, -0.03444771,  0.03680828, -0.02485601,  0.04545638],
       [-0.02065004,  0.03175913,  0.00026436, -0.03082453, -0.0021693 ,
         0.0027517 ,  0.03534675,  0.02553776,  0.02138444,  0.01912861],
       [-0.04712678, -0.00592683, -0.02656016,  0.01207193, -0.00208664,
         0.00302697,  0.02263913,  0.01174365